#!/bin/bash 

function SeleccionarHistorico() {
    fichero=$1

    if [ -e $fichero ]; then
        HISTFILE=$fichero

        export HISTFILE
    fi
}

function ElegirHistorico() {
    dir=`ls ~/.History/Histories | zenity --list --column "Seleccione Directorio"`
    if [ $dir != "" ]; then
        hist=`ls ~/.History/Histories/${dir} | zenity --list --column "Seleccione Histórico"`
    else
        zenity --info --text="Operación cancelada."
        . ${HOME}/.History/Scripts/exec
    fi
}

function NuevoHistorico(){

    touch ${HOME}/.History/.Temp/aux.temp
    SeleccionarHistorico ${HOME}/.History/.Temp/aux.temp
    bash

}

function GuardarHistorico(){
    echo $SHLVL
    zenity --question --text "Guardar?"
    if [ $? = 0 ];then
       
        mv ${HOME}/.History/.Temp/aux.temp ${HOME}/.History/Histories/Custom/`date +%y-%m-%d`
        HISTFILE=${HOME}/.bash_history
        zenity --info --text="Historico guardado."
    else 
        rm ${HOME}/.History/.Temp/aux.temp
        zenity --info --text="Historico descartado."
    fi
}
#Funcion de Porcentajes
function PorcentajeOrden(){
    ElegirHistorico
    numderepeticiones=fgrep -o "$1" ${HOME}/.History/Histories/$dir/$hist | wc -l
    lineastotales=wc ${HOME}/.History/Histories/$dir/$hist
    multiplicacion=expr $numderepeticiones\*100
    porcentajetotal=expr $multiplicacion/$lineastotales
    zenity --info --text="El porcentaje de veces que se repite esta orden es: $porcentajetotal."

}

#Funcion de Fusionar historicos
fuction FusionarHistoricos(){
    #Seleccion de Historicos
    dir=`ls ~/.History/Histories | awk '{print "FALSE\n"$0}' | zenity --list --checklist --column="Acceder?" --column="Directorios" --separator=" "`
    declare -A arrayHistoricos
    set $dir

    while [ $1 != "" ]
    do
        hist=`ls ~/.History/Histories/${1} | awk '{print "FALSE\n"$0}' | zenity --list --checklist --column="Fusionar?" --column="Históricos" --separator=" "`
        arrayHistoricos[$1]=$hist
        let count=count+1
        shift
    done
    #Establecemos nombre al fichero
    nombrehistorico=`date +%Y_%m_%d`".fusion" 
    #Bucle para fusionar los historicos que hemos definido de cada directorio
    for index in "${!arrayHistoricos[@]}"
    do
        directorio=$index
        ficheros="${arrayHistoricos[$index]}" 
        set $ficheros
            while [ $1 != "" ]
            do
                cat ${HOME}/.History/Histories/${directorio}/${1} >> "${HOME}/.History/Histories/Dates/$nombrehistorico"
                shift
            done    
    done
    zenity --info --text="Historico fusionado correctamente con el nombre $nombrehistorico."


}

#Funcion que permite elegir varios historicos de diferentes directorios y eliminarlos a la vez 
function EliminarHistoricos() {

    #Creamos un array asociativo que contenga para cada directorio seleccionado, una lista con los ficheros selecionados a borrar
    dir=`ls ~/.History/Histories | awk '{print "FALSE\n"$0}' | zenity --list --checklist --column="Acceder?" --column="Directorios" --separator=" "`
    declare -A arrayHistoricos
    set $dir

    while [ $1 != "" ]
    do
        hist=`ls ~/.History/Histories/${1} | awk '{print "FALSE\n"$0}' | zenity --list --checklist --column="Borrar?" --column="Históricos" --separator=" "`
        arrayHistoricos[$1]=$hist
        let count=count+1
        shift
    done
    #Comprobamos que ha ido bien la seleccion de ficheros
    if [ $? = 0 ]; then
        zenity --info --text="Operación completada."
    else
        zenity --info --text="Operación cancelada."
        . ${HOME}/.History/Scripts/manage
    fi

    #Bucle para borrar la lista de ficheros que hemos definido de cada directorio
    for index in "${!arrayHistoricos[@]}"
    do
        directorio=$index
        ficheros="${arrayHistoricos[$index]}" 
        set $ficheros
            while [ $1 != "" ]
            do
                rm ${HOME}/.History/Histories/${directorio}/${1}
                shift
            done    
    done
} 

function Importar() {
    rutaorigen=$1
    ficherooriginal=$(basename "$rutaorigen")
    fichero=$ficherooriginal
    rutadestino="${HOME}/.History/Histories/Custom/${fichero}"

    if [ -e $rutaorigen ]; then
        let count=0
        while [ -e $rutadestino ]
        do
            let count=${count}+1
            fichero=${ficherooriginal}"${count}"
            rutadestino="${HOME}/.History/Histories/Custom/${fichero}"
        done
        cp $rutaorigen $rutadestino
        if [ $? -eq 0 ]; then
            resultado="Fichero importado al directorio Custom con el nombre: ${fichero}"
        else
            resultado='Algo salio mal y no se pudo realizar la importación'
        fi
    fi
}

function Exportar() {
    dir=$1
    hist=$2
    rutaorigen="${HOME}/.History/Histories/${dir}/${hist}"
    ficherooriginal=$(basename "$rutaorigen")
    fichero=$ficherooriginal
    dirdestino=`zenity --file-selection --directory --filename=${HOME}/ --title="Seleccione Directorio de destino"`
    rutadestino="${dirdestino}/${fichero}"

    if [ -e $rutaorigen ]; then
        let count=0
        while [ -e $rutadestino ]
        do
            let count=${count}+1
            fichero=${ficherooriginal}"${count}"
            rutadestino="${dirdestino}/${fichero}"
        done
        cp $rutaorigen $rutadestino
        if [ $? -eq 0 ]; then
            resultado="Histórico exportado al directorio ${dirdestino} con el nombre: ${fichero}"
        else
            resultado='Algo salio mal y no se pudo realizar la exportación'
        fi
    fi
}