#!/bin/bash 
. ${HOME}/.History/Functions/Funciones

array=('Seleccionar Histórico' 'Gestión de Históricos' 'Información' 'Salir')
opcion=$(zenity --entry --title "MHIST" --text "Seleccione una opción." "${array[@]}")

case $opcion in
    'Seleccionar Histórico')
        ElegirHistorico
        if [ "$hist" != "" ]; then
            SeleccionarHistorico ${HOME}/.History/Histories/${dir}/${hist}
            if [ $result == true ]; then
                zenity --info --text="Histórico del sistema cambiado correctamente"
            else
                zenity --error --text="No se ha podido cambiar el histórico del sistema"
            fi
        else
            zenity --info --text="Operación cancelada."
            . ${HOME}/.History/Scripts/exec
        fi
        ;;
    'Gestión de Históricos')
        . ${HOME}/.History/Scripts/manage
        ;;
    'Información')
        . ${HOME}/.History/Scripts/info
        ;;
    *)
        zenity --info --text="Hasta pronto."
        ;;
esac