#!/bin/bash

array=('Ordenes mas utilizadas' 'Porcentaje de órdenes' 'Volver')
opcion=$(zenity --entry --title "Información de Históricos" --text "Seleccione una opción." "${array[@]}")

if [ "$opcion" == "Ordenes mas utilizadas" ]; then
    #Uso de Ordenes
    ElegirHistorico
    if [ $hist != "" ]; then
    UsodeOrdenes ${HOME}/.History/Histories/${dir}/${hist}
	else
    zenity --info --text="Operación cancelada."
    . ${HOME}/.History/Scripts/info
fi
    
elif [ "$opcion" == "Porcentaje de órdenes" ]; then
    #Porcentaje
    echo 'Porcentaje'
elif [ "$opcion" == "Volver" ] || [ "$opcion" == "" ]; then
    #Volver al menú principal
    . ${HOME}/.History/Scripts/exec
fi