#!/bin/bash

array=('Ordenes mas utilizadas' 'Porcentaje de órdenes' 'Volver')
opcion=$(zenity --entry --title "Información de Históricos" --text "Seleccione una opción." "${array[@]}")

if [ "$opcion" == "Ordenes mas utilizadas" ]; then
    #Top
    echo 'Mas usadas'
elif [ "$opcion" == "Porcentaje de órdenes" ]; then
    #Porcentaje
    echo 'Porcentaje'
elif [ "$opcion" == "Volver" ] || [ "$opcion" == "" ]; then
    #Volver al menú principal
    . ${HOME}/.History/Scripts/exec
fi