#!/bin/bash 
. ~/.History/Functions/Funciones

array=('Nuevo Histórico' 'Guardar Histórico' 'Eliminar Históricos' 'Desglosar Histórico' 'Fusionar Históricos' 'Importar/Exportar' 'Volver')
opcion=$(zenity --entry --title "Gestión de Históricos" --text "Seleccione una opción." "${array[@]}")

if [ "$opcion" == "Nuevo Histórico" ]; then
    #Nuevo Histórico
    NuevoHistorico
elif [ "$opcion" == "Guardar Histórico" ]; then
    #Guardar Histórico activo (solo si no esta guardado ya)
    GuardarHistorico
elif [ "$opcion" == "Eliminar Históricos" ]; then
    #Eiminar Históricos
    EliminarHistoricos
elif [ "$opcion" == "Desglosar Histórico" ]; then
    #Desglosar por orden
    echo 'Desglosar'
elif [ "$opcion" == "Fusionar Histórico" ]; then
    #Fusionar Históricos
    FusionarHistoricos
elif [ "$opcion" == "Importar/Exportar" ]; then
    #Importar/Exportar
    opcion=$(zenity --entry --title "Importar/Exportar" --text "Que acción desea realizar" "Importar" "Exportar")
    if [ "$opcion" == "Importar" ]; then
        #Importar
        hist=`zenity --file-selection --filename=${HOME}/ --title="Select a File"`
        if [ $hist != "" ]; then
            Importar $hist
            zenity --info --text="${resultado}"
        fi
    elif [ "$opcion" == "Exportar" ]; then
        #Exportar
        ElegirHistorico
        if [ $hist != "" ]; then
            Exportar $dir $hist
            zenity --info --text="${resultado}"
        fi
    else
        #Volver al menú principal
    . ${HOME}/.History/Scripts/exec
    fi
elif [ "$opcion" == "Volver" ] || [ "$opcion" == "" ]; then
    #Volver al menú principal
    . ${HOME}/.History/Scripts/exec
fi